### ISSUE TITLE
“boost/config.hpp”: No such file or directory

### ISSUE THREAD

**Issue by yujream** [boostorg/geometry#1348] opened 2024-11-25 08:37 UTC
In the Develop branch, I included the `Include` folder into my project. When compiling, it is prompted that I can't find the `config.hpp` file. What should I do, thank you!

**Comment by vissarion** [comment] 2024-11-25 12:15
It is probably related to your local setup and how you include directories while compiling.

**Comment by yujream** [comment] 2024-11-25 15:38
> It is probably related to your local setup and how you include directories while compiling.

I did not find the `config.hpp` file under the `include/boost/` folder. Do I need to put the `boost.geometry` module under the complete boost library?

**Comment by barendgehrels** [comment] 2024-11-25 18:12
It's here: https://github.com/boostorg/config/blob/5e98c6ddd4d58311b52e8f0fdde38c80c04f70ae/include/boost/config.hpp

`Boost.Geometry` depends on several other `Boost` libraries. So if you want to work with it, you cannot just download Develop and go. You should either have Boost installed somewhere, and point to it, or first download the Boost Super project.

The same holds for most Boost libraries, so it is not documented explicitly.

https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview

Closing as not a bug (you can ask questions in the `Discussion` tab)

**Closed by barendgehrels** 2024-11-25 18:12 UTC
Labels: not a bug

**Comment by yujream** [comment] 2024-11-26 07:25
> It's here: https://github.com/boostorg/config/blob/5e98c6ddd4d58311b52e8f0fdde38c80c04f70ae/include/boost/config.hpp
> 
> `Boost.Geometry` depends on several other `Boost` libraries. So if you want to work with it, you cannot just download Develop and go. You should either have Boost installed somewhere, and point to it, or first download the Boost Super project.
> 
> The same holds for most Boost libraries, so it is not documented explicitly.
> 
> https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview
> 
> Closing as not a bug (you can ask questions in the `Discussion` tab)

I will try it, thank you for answering!
