### ISSUE TITLE
Regression 1.78.0 - 1.79.0 (still in 1.82.0): difference of two polygons gives unexpected empty result

### ISSUE THREAD

**Issue by gastald88** [boostorg/geometry#1138] opened 2023-04-21 10:07 UTC
I have two polygons p1 and p2, where the difference p1 - p2 is clearly non-empty (see image, p1 blue, p2 orange), but the difference operation returns an empty polygon.

![image](https://user-images.githubusercontent.com/37936526/233601244-b9849164-f69c-4fe0-b408-35766b321960.png)

Here below a godbolt link to replicate this problem:
https://godbolt.org/z/YTjM3GG1G

The result is correct in boost version 1.78.0 (you can set at the godbolt platform in the compiler arguments `-I/opt/compiler-explorer/libs/boost_1_78_0)`

From version 1.79.0 on (until the 1.82.0 that I recentely tested on my local environment) the result is incorrect.

I also tried to define the macro BOOST_GEOMETRY_ROBUSTNESS_ALTERNATIVE, but the bug is still there.

**Comment by vissarion** [comment] 2023-06-16 14:39
Thanks for filing this issue.

I can reproduce your issue locally.  

However, defining BOOST_GEOMETRY_ROBUSTNESS_ALTERNATIVE (before all includes) is working for me.
This seems to be one regression of rescaling removal in 1.79.

**Comment by barendgehrels** [comment] 2023-09-14 08:36
Fixed by commit eb879fe62
It now also works without rescaling.
I will create a unit test and close the issue.

**Closed by barendgehrels** 2023-09-14 08:36 UTC

**Comment by barendgehrels** [comment] 2023-09-14 17:28
Unit test in #1202
