### ISSUE TITLE
spherical polygon area

### ISSUE THREAD

**Issue by swannyPeng** [boostorg/geometry#395] opened 2017-04-19 15:14 UTC
Hi，
there may be a bug in calculating the area of spherical polygon. when the polygon 's verticals contain north polar,the result is right ,but when containing south polar, it returns a wrong result.
I have tested POLYGON((0 0,90 0,0 -90,0 0)), we expect to 1.57249 but returning 2.02365.
swanny

**Comment by awulkiew** [comment] 2017-07-28 02:04
What version of Boost are you using? develop and 1.64 seems to be fine.

My test:

    typedef bg::model::point<double, 2, bg::cs::spherical_equatorial<bg::degree> > point;
    typedef bg::model::polygon<point> polygon;

    polygon poly1, poly2;
    bg::read_wkt("POLYGON((0 0,90 0,0 -90,0 0))", poly1);
    bg::read_wkt("POLYGON((0 0,0 90,90 0,0 0))", poly2);

    double a1 = bg::area(poly1);
    double a2 = bg::area(poly2);

I'm getting `1.5707963267948963` in both cases. The same for `float` coordinate type.

**Comment by awulkiew** [comment] 2017-12-14 22:56
I cannot reproduce it so I'm going to close this issue. You didn't confirm or deny that the code above works for you so reopen this issue if needed. For now I'll assume that in recent versions of Boost the problem is fixed.

**Closed by awulkiew** 2017-12-14 22:56 UTC
