### ISSUE TITLE
Union producing self intersections after 1.78

### ISSUE THREAD

**Issue by jpan127** [boostorg/geometry#1229] opened 2024-01-16 19:52 UTC
`Minimal Reproducible Example`: https://godbolt.org/z/Tdb51rcY8

Hi, I have been `union_`ing a set of triangular polygons. Our repo recently updated from `1.71` to `1.82` which broke one of our union functions. The above example takes 2 triangles, that share an edge, and unions them. The result contains duplicate points and fails `boost::geometry::is_valid`.

All versions from `1.79 onwards` fails this example.

I noticed that the release notes (https://beta.boost.org/doc/libs/1_79_0/libs/geometry/doc/html/geometry/release_notes.html) show issue (https://github.com/boostorg/geometry/issues/838) which mentions `BOOST_GEOMETRY_NO_ROBUSTNESS`. Defining that for `1.71` also leads to the same failure if that gives any hints.

**Comment by barendgehrels** [comment] 2024-03-03 09:50
Thanks for the report. I cannot reproduce it anymore. It is fixed by 68a225daf

**Comment by barendgehrels** [comment] 2024-03-03 22:45
I'll close the issue because it is fixed and a testcase has been added.

**Closed by barendgehrels** 2024-03-03 22:45 UTC

**Comment by cjamin** [comment] 2024-03-05 07:55
Will this fix be released with Boost 1.85?
