### ISSUE TITLE
9438-returns: call of overloaded ‘ignore_unused_variable_warning(...)’ is ambiguous

### ISSUE THREAD

**Issue by Magnati** [boostorg/geometry#513] opened 2018-10-08 11:27 UTC
Hello dear team of Boostorg.

First, I am not sure wheter this is the right repository to post this issue, if not, I will grandly repost it somewhere else.

The error is pretty much the same as in the closed issue [#9438](https://svn.boost.org/trac10/ticket/9438#no1) and I am not sure why it reappeared.

- OS: Ubuntu 18.04 Bionic Beaver
- clang: 6.0
- lemon: 1.3.1
- boost: happened under 1.63 and  was reproduced with boost 1.68

```c++
#include <boost/geometry.hpp>
#include <lemon/list_graph.h>

namespace bg = boost::geometry;
namespace bgi = boost::geometry::index;

using Point = boost::geometry::model::point<double, 2, bg::cs::cartesian>;
using Graph = lemon::ListDigraph;
using Node = lemon::ListDigraph::Node;
typedef std::pair<Point, Node> Pair;
using BoostRTree = bgi::rtree<Pair, bgi::quadratic<16>>;
using BoostQueryResult = std::vector<Pair>;

int main()
{
	Point one = Point(10, 51);
	Point two = Point(10, 51);
	BoostRTree rtreePair = BoostRTree();
	Graph graph;
	Node dummy1 = graph.addNode();
	Node dummy2 = graph.addNode();

	rtreePair.insert(std::make_pair(one, dummy1));	
	return 0;
}

```

**Comment by mloskot** [comment] 2018-10-08 12:49
FYI, a `lemon`-stripped version of your example:

```
#include <boost/geometry.hpp>

namespace bg = boost::geometry;
namespace bgi = boost::geometry::index;

using Point = boost::geometry::model::point<double, 2, bg::cs::cartesian>;
struct Node {};
struct Graph { Node addNode() { return Node(); } };
typedef std::pair<Point, Node> Pair;
using BoostRTree = bgi::rtree<Pair, bgi::quadratic<16>>;
using BoostQueryResult = std::vector<Pair>;

int main()
{
    Point one = Point(10, 51);
    Point two = Point(10, 51);
    BoostRTree rtreePair = BoostRTree();
    Graph graph;
    Node dummy1 = graph.addNode();
    Node dummy2 = graph.addNode();

    rtreePair.insert(std::make_pair(one, dummy1));	
    return 0;
}
```

It does not seem to reproduce the problem using Boost.Geometry from the Boost 1.68.0, its `master`and `develop` branches. Tried clang 6.0 and GCC 8.2

**Comment by awulkiew** [comment] 2018-10-08 17:50
In all cases `boost` namespace is specified in Boost.Geometry.  It could help if you pasted the compiler output or say in which file exactly the ambiguous call of `ignore_unused_variable_warning` is detected.

Side note: instead of using `boost::ignore_unused_variable_warning` from ConceptCheck we should use `boost::ignore_unused` from Core consistently. We use both now.

**Comment by mloskot** [comment] 2018-10-12 09:58
@awulkiew See #514

**Comment by awulkiew** [comment] 2018-10-12 13:31
@mloskot Thanks!

Still I think the problem @Magnati has is not caused by Boost.Geometry. He didn't write anything more so it's impossible to know for sure but with your improvement it should definitely not cause any problems. So I'm closing this issue

**Comment by mloskot** [comment] 2018-10-12 13:36
Yes, I agree. I just wanted to clear any possibility for this issue to be caused by Boost.Geometry.

**Closed** 2018-10-12 18:08 UTC
Labels: invalid
