### ISSUE TITLE
runtime error deserialization rtree crash due to load factor

### ISSUE THREAD

**Issue by addy90** [boostorg/geometry#962] opened 2022-01-13 12:09 UTC
I discovered a crash in the experimental rtree deserialization feature.

In some cases, the following exception is raised:
```
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: rtree loading error
```

The error comes from here, the test exactly above fails in certain conditions when the element_count is too low in my case:
https://github.com/boostorg/geometry/blob/394461f773f6003a20c8ebaf06c1f92857e31c8f/include/boost/geometry/index/detail/serialization.hpp#L417

I can replicate the error with the attached source code (Boost Unit Test), please rename to `.cpp`: 
[rtree_serialization_test.txt](https://github.com/boostorg/geometry/files/7862513/rtree_serialization_test.txt)

`BOOST_GEOMETRY_INDEX_DETAIL_EXPERIMENTAL` is enabled.

I have two settings in line 17 and 18. With `POINTS = 100` the loading crashes always, with `POINTS 200` it does not crash in both tests! So it clearly has to do with the loading of the tree. There are surely other options that also make it crash or work but these two should be sufficient to replicate the problem.

When I remove or comment line 415 to 417 from (so when I remove the test and the exception) both my cases work:
https://github.com/boostorg/geometry/blob/394461f773f6003a20c8ebaf06c1f92857e31c8f/include/boost/geometry/index/detail/serialization.hpp

In my case, `max_elements` is 16 and `min_elements` when I compute it from here should be `4`:
https://github.com/boostorg/geometry/blob/394461f773f6003a20c8ebaf06c1f92857e31c8f/include/boost/geometry/index/parameters.hpp#L33

The test here fails because my `element_count` is only `3`, so the tree is "underloaded":
https://github.com/boostorg/geometry/blob/394461f773f6003a20c8ebaf06c1f92857e31c8f/include/boost/geometry/index/detail/serialization.hpp#L415

I am not sure if the rtree packing algorithm allows for "underloaded" rtrees but it looks like this is happening. The rtree is not loaded as the deserialization expects it. So when the test is removed, it works because the rtree is in fact valid concerning the rest of the source code.

I conclude that this means that the test from line 415 to 417 is wrong and either needs to be removed or redefined to work in all valid cases. I am not sure if more cases exist apart from the two I provided.

I hope you are able to replicate my error with the provided code and suggestions. Thank you for your great work on Boost::geometry!

**Comment by addy90** [comment] 2022-01-13 13:42
I just noticed this was similarly posted here: #865
But the fix was only for the root node, it seems that it still happenes as we can see in my example.

**Comment by awulkiew** [comment] 2022-01-13 15:00
Thanks for the report! I can reproduce it. Yes, you seem to be correct that the current level should be checked instead since root node can contain less elements than min no matter how big is the rtree.

Btw, there is a utility for checking the correct numbers of nodes and elements count < min is only checked for current_level > 0:
https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/index/detail/rtree/utilities/are_counts_ok.hpp#L86

**Comment by awulkiew** [comment] 2022-01-13 22:18
I think you're correct. While preparing the previous fix I probably thought that min count can be ignored only in rtrees containing one leaf root node. I must have forgotten than root can contain lesser number of elements than min no matter how many nodes there are in the rtree.

**Comment by addy90** [comment] 2022-01-14 07:41
The reason sounds plausible to me!
I can at least tell that in my real scenario, I serialized huge point and segment rtrees with about 2.5 million respectively 5 million entries in binary files. With the patch applied, the deserialization finally worked in all cases I have tested yet! Deserialization is much faster than recreation of such large trees.
So thank you for providing an official patch!

**Closed** 2022-01-19 23:36 UTC
Labels: bug
