### ISSUE TITLE
Difference: not the right set of points returned. Rounding issue?

### ISSUE THREAD

**Issue by ghost** [boostorg/geometry#1111] opened 2023-02-01 06:59 UTC
Hi,

Please have a look at [the issue on godbolt](https://godbolt.org/z/v94vceE1K).

As you can see, points are disappearing when they should not.
My issue is that I suspect rounding to remove some points that should be kept on the polygon after applying a difference.
Missing points are my main concern, I've been caught because I use your library for game development. 

Type is double so we should not have such an issue with such large (0.05) absolute coordinates difference.

I disabled the optimisation because otherwise Goldbolt complained about compilation time too long (may be a temporary issue).

Is there an immediate workaround ?

Thanks

**Comment by LumiereDeLOmbre** [comment] 2023-02-01 07:54
The issue arise because the points are touching the segment.

Maybe at some point the algorithm decides that they are unimportant, but they are to me. They work as tags/locations markers.

Applying a very small buffer could be an immediate workaround but it adds a lot of point and mess with the rest of my code.

The only way to do it right now is to manually add the points back in a loop.

Keeping the points in place on the edges in the first place would avoid this. Maybe add an option?

**Comment by barendgehrels** [comment] 2023-03-15 10:18
The issue is gone on godbolt... `Whoops, ID "v94vceE1K" could not be found` Can you please add it again?

**Comment by barendgehrels** [comment] 2024-11-24 10:19
Verified with 1.87 (beta), behaviour is fully OK AFAICS
Closing issue.

```
"POLYGON((0 0,8 0,8 10,0 10,0 0))",
"POLYGON((8 9,12 9,12 9.95,8 9.95,8 9))",
"MULTIPOLYGON(((8 10,0 10,0 0,8 0,8 10)))",
"POLYGON((8 8.5,12 8.5,12 8.95,8 8.95,8 8.5))",    
```
->
```
issue_1111_a<d> a: 80 b: 3.8 union: 83.8 intersection: 0 diff(a-b): 80 diff(b-a): 3.8 sym_diff: 83.8    checks: 0 0 0 0 OK OK OK OK
issue_1111_b<d> a: 80 b: 1.8 union: 81.8 intersection: 0 diff(a-b): 80 diff(b-a): 1.8 sym_diff: 81.8    checks: 0 0 0 0 OK OK OK OK

```

**Closed by barendgehrels** 2024-11-24 10:19 UTC
